### ISSUE TITLE
[META] Fragile stuff

### ISSUE THREAD

**Issue by ThomasBuchinger** [ThomasBuchinger/automate-gitflow#2]
List of things that is still pretty fragile=
- [x] Rebase: Import fails if FEATURE is not rebased on MASTER, because MASTER can have changed files not  present in FEATURE (or worse present, but old!)
- [x] Script leaves repository with DETACHED_HEAD 
- [ ] Changes in Multiple Domains are not handled.

**Comment by ThomasBuchinger** [comment]
fix 1 & 2 by allowing to clone the repository on every script run and creating a local branch respectively
3 will be handled in a new issue
/close
